project:
  type: website
  output-dir: "docs"

website:
  title: "Murli Manohar"
  favicon: mmb.png
  navbar:
    left: 
      - text: Home
        file: index.qmd
      - text: Conferences
        file: conferences.qmd
      - text: Teaching
        file: teaching.qmd

format:
  html:
    fontsize: 1.1rem
    theme:
      - cosmo
      - brand
    css: styles.css



